import Vue from 'vue'
import { NavBar, Form, Field, Loading, Button, Tabbar, TabbarItem, Icon, Tab, Tabs, Cell, List, PullRefresh, ActionSheet, Popup, Row, Col, Badge, Search, Divider, Tag, CellGroup, Image as VanImage, Dialog, DatetimePicker, Lazyload } from 'vant'
Vue.use(Loading)
Vue.use(VanImage)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Icon)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Cell)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(ActionSheet)
Vue.use(Popup)
Vue.use(Row)
Vue.use(Col)
Vue.use(Badge)
Vue.use(Search)
Vue.use(Tag)
Vue.use(CellGroup)
Vue.use(VanImage)
Vue.use(Dialog)
// 封装中间件函数插件

// use就是调用函数中的install方法,传的参数是Vue，是固定搭配
Vue.use(Divider)
Vue.use(DatetimePicker)
Vue.use(Lazyload)
